### ISSUE TITLE
Setting up

### ISSUE THREAD

**Issue by svj13** [NewMotion/ocpp#17]
Hello :)

I am new to OCPP and really want to give this a go. I am having a lot of difficulty actually setting up the project however. :(
I can't seem to be able to add a pom file. Trying to set up the project as maven and then importing in hasn't been successful so far. Also the build fails "missing dependency 'object java.lang.Object in compiler mirror"

Are you (or anyone else) able to help me set it up? I would greatly appreciate it

I originally tried setting it up using Atom. I am now trying to use IntelliJ

**Comment by reinierl** [comment]
Most of us here are using IntelliJ to develop the code, so that should definitely work.

Be aware that this project uses SBT as the build tool, not Maven. You should be able to use the "File" -> "Open..." dialog to configure it correctly. If you use that option, does the caption of the import dialog say "Import Project from SBT"? I think it should.

**Comment by svj13** [comment]
thank you :) that fixed it.

I am now having trouble running the example (I am using windows powershell).

I searched around a bit but nothing was specific to sbt

![image](https://user-images.githubusercontent.com/18566065/33810200-e0ea2360-de66-11e7-8302-cdf8c8e87f4c.png)

**Comment by poohsen** [comment]
those quotes around `1.0.4` are messing up the path to your sbt.jar. something seems off with your sbt installation

**Comment by svj13** [comment]
I have tried reinstalling from a few different sources. I installed the correct version for this project, and also tried using Windows cmd as a workaround. 

https://stackoverflow.com/questions/47744245/running-a-sbt-command-from-windows-powershell-unable-to-access-jar

Do you know how I might be able to fix this?

**Comment by poohsen** [comment]
I'm not on windows so no clue, sry. let's hope somebody with windows will answer your SO question

**Comment by reinierl** [comment]
Closing because this looks like an SBT installation issue not related to this project.

By the way, is there any chance that the path in your question is getting cut off at  a space? '
\.sbt\preloaded\org.scala-sbt\sbt\"1.0.4"\jars\sbt.jar' looks as if there should be something in front of it. But for me too, I haven't used Windows in years, and I don't remember ever using Powershell.
